name = "geodesic-fortran"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2012-2023, Charles Karney, Jacob Williams"
license = "BSD-3"
description = "Fortran implementation of geodesic routines"
homepage = "https://github.com/jacobwilliams/geodesic-fortran"

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = true